### ISSUE TITLE
0x10-app-security-risks.md 表の項目名との用語統一

### ISSUE THREAD

**Issue by ogis-sanae** [okdt/Top10#13]
あなたにとってのリスク
現状：OWASP Risk Rating Methodologyに基づいた以下の格付手法により、発生可能性と技術的な影響について評価します。
原文：likelihood and technical impact
提案：OWASP Risk Rating Methodologyに基づいた以下の格付手法により、発生可能性と技術面への影響について評価します。

Risk Ratingの翻訳では、「技術的な影響」としましたが、今後「技術面への影響」で統一されると思いますので、ここでも合わせておいた方が良いのではないかと思います。

**Comment by okdt** [comment]
賛成です。お願いします。

**Comment by okdt** [comment]
「以下に示すOWASP Risk Rating Methodologyに基づいた格付手法により、発生可能性と技術面への影響について評価します。」なんてどうかしら。

**Comment by ogis-sanae** [comment]
賛成です。より滑らかな翻訳と思います。修正完了いたしました。
