### ISSUE TITLE
0x11-t10.md 用語の統一 「機微な情報」

### ISSUE THREAD

**Issue by ogis-sanae** [okdt/Top10#14]
sensitive dataは一律「機微な情報」と翻訳しておいた方が、一貫性があってよいのではないかと思います。※一部議論の余地があります。

現状：財務情報、健康情報や個人情報といった機密データを適切に保護していません。
原文：do not properly protect sensitive data, such as financial, healthcare, and PII.
提案：財務情報、健康情報や個人情報といった機微な情報を適切に保護していません。

現状：機微なデータは特別な措置を講じないでいると
原文：Sensitive data may be compromised without extra protection,
提案：機微な情報は特別な措置を講じないでいると

現状：機微情報を含む冗長なエラーメッセージ
原文：and verbose error messages containing sensitive information.
提案：機微な情報を含む冗長なエラーメッセージ
※ここは、informationで、dataと区別がありますが、日本語では「データ」を「情報」と訳しているので、ここはどちらも「情報」と訳す他ないのかと思います。もしくは、「機微なデータ」と「機微な情報」を区別する必要があると思います。

**Comment by okdt** [comment]
提案１、２、３ともに賛成です。

データベースの話をしている文脈だったりするとデータとしたままのほうが良いかと思いますが、
そうでなければ基本的に統一してもいいと思います。よきにご判断くださり、修正してください。

**Comment by okdt** [comment]
あ、やります。

**Comment by okdt** [comment]
done
