### ISSUE TITLE
「脆弱性発見のポイント」への統一

### ISSUE THREAD

**Issue by ogis-sanae** [okdt/Top10#15]
Slackでの議論により、「脆弱性有無の確認」は「脆弱性発見のポイント」に変更になったと思います。
他に異論がなければ、「脆弱性発見のポイント」に統一します。

**Comment by okdt** [comment]
お願いします。

**Comment by ogis-sanae** [comment]
ちょっとコミットが被ってしまいコンフリクトの解決が走りましたが、修正完了しました。
