### ISSUE TITLE
0xa2-broken-authentication.md パスワードオラクル

### ISSUE THREAD

**Issue by ogis-sanae** [okdt/Top10#16]
①
パスワードオラクルは、翻訳しないと意味が伝わり辛いと思います。
ここでのオラクルは、神託を与える神としての意味と思います。
もう少し、意訳出来ると良いとは思うのですが、下記ではどうでしょうか？

現状：アプリケーションが自動化された攻撃やアカウントリスト攻撃に対策していない場合、そのアプリケーションがID/パスワードの組み合わせが正しいか検証するパスワードオラクルとして悪用されるかもしれません。
原文：If an application does not implement automated threat or credential stuffing protections, the application can be used as a password oracle to determine if the credentials are valid.
提案：アプリケーションが自動化された攻撃やアカウントリスト攻撃に対策していない場合、そのアプリケーションがID/パスワードの組み合わせが正しいか検証するパスワードの予言者として悪用されるかもしれません。

②
蔓延度としたので、蔓延に調整した方が適切かと思います。
現状：認証の不備が広く流行しています。
提案：認証の不備が広く蔓延しています。

**Comment by okdt** [comment]
強力なツール、くらいにしちゃえば良いのでは（案）

**Comment by ogis-sanae** [comment]
あ、そうですね。あえてのオラクル感は不要ですね。

提案：アプリケーションが自動化された攻撃やアカウントリスト攻撃に対策していない場合、そのアプリケーションが、強力なパスワード検証ツールとして、ID/パスワードの組み合わせの検証に悪用されるかもしれません

**Comment by okdt** [comment]
いいと思います！

**Comment by okdt** [comment]
検証がダブってるけど

**Comment by okdt** [comment]
If an application does not implement automated threat or credential stuffing protections, 
the application can be used as a password oracle to determine if the credentials are valid.

アプリケーションに自動化された攻撃やアカウントリスト攻撃の対策が実装されていないなら、そのアプリケーションは「強力なパスワード検証ツール」として認証情報の有効かどうかを調べるのに悪用されかねません。
