### ISSUE TITLE
0xa2-broken-authentication.md  防止方法の末尾の行の翻訳

### ISSUE THREAD

**Issue by ogis-sanae** [okdt/Top10#17]
日本語が一部不自然な感じが致しました。下記の翻訳案では如何でしょうか？

現状：フレームワークなどが標準で提供するセッション管理機構をサーバサイドで採用して、ログイン後に高いエントロピーを持つランダムなセッションIDを生成する。セッションIDはURLを含めず、セキュアに保存し、ログアウト・一定時間操作がない・一定期間のタイムアウトした後に無効にすべきである
原文： Use a server-side, secure, built-in session manager that generates a new random session ID with high entropy after login. Session IDs should not be in the URL, be securely stored and invalidated after logout, idle, and absolute timeouts.
提案：フレームワークなどが標準で提供するセッション管理機構をサーバサイドで使用し、ログイン後に十分にランダムなセッションIDを生成する。セッションIDはURLに含めるべきではなく、セキュアに保存する。また、ログアウト後や、一定時間操作がない、もしくは一定時間経過しタイムアウトしたセッションは無効にすべきである

**Comment by okdt** [comment]
改善部分だけに絞ると、エントロピーのところだけ？
「高いエントロピーを持つランダムなセッションID」は、結構エンジニアリングの香りがしていいけどなー。ランダマイザーがバカってことは結構あることなので。

**Comment by okdt** [comment]
にしても、原案も、ビルトインの、で良いところなのに、ずいぶん足しこんでいますね。前リリース踏襲なのかな。

**Comment by ogis-sanae** [comment]
セッションIDはURLを含めず。と、羅列したところを読みやすくしました。
エントロピー戻してみました。十分に～はエントロピーが、用語として難しいので残しました。
足し込んだ部分は、オリジナルのアイディアのようです。特に2013にはこのような防止方法はありませんでした。分かりやすくて良いかもとは思います。

提案：フレームワークなどが標準で提供するセッション管理機構をサーバサイドで使用し、ログイン後に高エントロピーで十分にランダムなセッションIDを生成する。セッションIDはURLに含めるべきではなく、セキュアに保存する。また、ログアウト後や、一定時間操作がない、もしくは一定時間経過しタイムアウトしたセッションは無効にすべきである

**Comment by okdt** [comment]
有象無象のフレームワークがセキュアなセッションマネージャを提供するとは限らないので、あえて「セキュアな」という言葉を残しました。セッションマネージャをうかつに自前で作るなというニュアンスもあろうかと思い、ビルトインのとしました。文末は「すべき」ではなく「する」で止めました。（他の箇条書きの文章にあわせた）

Thanks
