### ISSUE TITLE
0xa2-broken-authentication.md 攻撃シナリオ#2

### ISSUE THREAD

**Issue by ogis-sanae** [okdt/Top10#18]
原文の意図と少し違うように思います。

現状：パスワードが認証の一要素として使われ続けていることから、ほとんどの認証に関連する攻撃が起こっています。ユーザが脆弱なパスワードを設定、または再利用しやすい状況にないか、かつてのベストプラクティス、パスワード変更および複雑性の要件をレビューしてください。組織には、NIST 800-63におけるプラクティスの実装をやめること、多要素認証を採用することを推奨します。
原文：Most authentication attacks occur due to the continued use of passwords as a sole factor. Once considered best practices, password rotation and complexity requirements are viewed as encouraging users to use, and reuse, weak passwords. Organizations are recommended to stop these practices per NIST 800-63 and use multi-factor authentication.
提案：ほとんどの認証に関連する攻撃は、パスワードを唯一の要素として使い続けているため発生しています。これまで、ベストプラクティスと思われていた、パスワードの定期変更や複雑度の要件は、ユーザーに弱いパスワードの使用や再利用を奨励しているようなものでした。組織は、NIST 800-63に従いこれらの運用を辞め、多要素認証を採用することが推奨されます。

**Comment by okdt** [comment]
Thanks.

しかしこの文章、「シナリオ」なのは最初の1文だけですよね・・・続く部分は勧告ですものね。
