### ISSUE TITLE
0xa3-sensitive-data-disclosure.md 機密データ⇒機微な情報

### ISSUE THREAD

**Issue by ogis-sanae** [okdt/Top10#19]
元々が機密データだったので、文中に機密データが残っています。

・機密データを狙ったものです。機密データが暗号化され
 is simply not encrypting sensitive data./
・クレジットカードなどの機密データが含まれています。
 this information includes sensitive personal information (PII) data 
・個人データやビジネス上の機密データは特別に（that dataでしかないが用語の選択として）
 personal information and business secrets require extra protection, particularly if that data falls
・必要ない機密データを保存しない。できる限りすぐにそのような機密データを破棄するか、
 Don't store sensitive data unnecessarily.Discard it as soon as possible or use PCI DSS compliant tokenization or even truncation. Data that is not retained cannot be stolen.
・保存時にすべての機密データを暗号化しているか確認する
Make sure to encrypt all sensitive data at rest.

**Comment by okdt** [comment]
Thanks.
