### ISSUE TITLE
0xa3-sensitive-data-disclosure.md 防止方法の未翻訳箇所

### ISSUE THREAD

**Issue by ogis-sanae** [okdt/Top10#21]
work factor(delay factor)が翻訳されていない。
私もハッシュの専門ではないのですが、[この解説](https://ja.stackoverflow.com/questions/21636/%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AE%E3%83%91%E3%82%B9%E3%83%AF%E3%83%BC%E3%83%89%E3%81%AE%E3%83%8F%E3%83%83%E3%82%B7%E3%83%A5%E6%96%B9%E5%BC%8F-%E4%BA%92%E6%8F%9B%E6%80%A7-%E7%85%A7%E5%90%88%E6%96%B9%E6%B3%95%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)によると計算負荷の事のようです。
Argon2の[Wiki](https://ja.wikipedia.org/wiki/Argon2)を見ると少し翻訳のヒントがありそうです。

現状：Argon2、scrypt、 bcrypt、PBKDF2のように、十分な暗号強度があり、work factor (delay factor)を使えるソルト化ハッシュ関数でパスワードを保存する
原文：Store passwords using strong adaptive and salted hashing functions with a work factor (delay factor), such as [Argon2], [scrypt], [bcrypt]or [PBKDF2].
提案：Argon2、scrypt、 bcrypt、PBKDF2のように、強い耐性と実行時間（遅延要素）をパラメータとして制御出来るソルト付のハッシュ関数を使ってパスワードを保存する

※Adaptiveを適応性のように訳すと良くわからなくなるので、ハッシュの強さは、耐性で表現されるので、意訳しました。

**Comment by okdt** [comment]
現状：work factor (delay factor)を使えるソルト化ハッシュ関数
提案：強い耐性と実行時間（遅延要素）をパラメータとして制御出来るソルト付のハッシュ関数

原文はwork factorの主な例としてdelay factorを挙げる記載方法です。
ハッシュのプログラミング関数リファレンスなどを見れば、 work factorはワークファクタと記載しているほうがエンジニアにはわかるのではないかと思います。delay factorは時間をかけて複雑さを増すという方式を指していることが伝われば良いレベルかと思いますので、遅延という言葉を使いたいと思います。
またこのチートシートの翻訳も、ワークファクタとしているままですが、これは無理に日本語にしないほうが良い例かなと（伸ばし棒に揺らぎがあるなどツッコミどころはあるとはいえ・・・）
https://jpcertcc.github.io/OWASPdocuments/CheatSheets/PasswordStorage.html

strong adaptive and salted hashing functions は、強くかつ適応可能なレベルのソルト付きハッシュ関数を使えという意味ですのでそういう訳にしておきます。

Thanks.
