### ISSUE TITLE
0xa3-sensitive-data-disclosure.md　脆弱性発見のポイント内、読点の修正提案

### ISSUE THREAD

**Issue by Chibitrin** [okdt/Top10#24]
＜現訳文＞
初期値のままの暗号鍵の使用、弱い暗号鍵を生成または再利用、適切な暗号鍵管理、鍵のローテーションをしていない、これらの該当する箇所はないか。

上記訳につきまして、「適切な暗号鍵管理」のみ、読点（、）の位置のせいか正しいことをしているものが含まれてしまっているように感じます。原文は「proper key management or rotation missing」ですので、「proper key management missing」が伝わる必要があると考えます。

よって、読点を接続詞に置き換えて「適切な暗号鍵管理または鍵のローテーションをしていない」とするか、読点を生かすのであれば「不適切な暗号鍵管理」と言い換えるのはいかがでしょうか。

**Comment by shonantoka** [comment]
接続詞に置き換える対応をとりました。
