### ISSUE TITLE
校正上の修正提案（てにをは、用語統一、表現統一など）

### ISSUE THREAD

**Issue by Chibitrin** [okdt/Top10#25]
以下、恐縮ながら修正点の提案をいたします。

１．0x05-introduction.md　（てにをは）

「謝辞」の部分

そして最後に、世界中でOWASP Top 10にもっと手に取りやすくするため、
↓
そして最後に、世界中でOWASP Top 10をもっと手に取りやすくするため、

@ogis-sanaeが下記の２は、修正済みです。
> ２．0x06-release-notes.md　（表示方法確認）
> 「統合、引退。ただし、忘れて良いという意味ではない」の部分
> **A8-クロスサイトリクエストフォージェリ (CSRF)**は、
> 上記はこのままでよいですか。本来太字になるべきものでしょうか。

３．0xa2-broken-authentication.md　（他の項目との表現統一）

「セキュリティ上の弱点」の部分

（現訳）
一般的にユーザ認証とアクセス制御を設計・実装するため、認証の不備が広く流行しています。

（修正案１）
一般的にユーザ認証とアクセス制御を設計・実装するため、認証の不備がよく見られます。

（修正案２）
多くのユーザ認証やアクセス制御の設計・実装が不適切なために、認証の不備がよく見られます。

４．0xa3-sensitive-data-disclosure.md　（てにをは、ねじれ）

「影響」部分

保護に失敗し保護すべきすべての情報を台無しになることは頻繁に生じています。
↓
保護に失敗し保護すべきすべての情報が台無しになることは頻繁に生じています。

「脆弱性発見のポイント」部分

データが、EUの一般データ保護規則(GDPR)のようなプライバシー関連の法律が適用される場合、また、PCIデータセキュリティスタンダード(PCI DSS)など金融の情報保護の要求があるような規定がある場合には、特に注意が必要です。
↓
主部と述部でねじれがあります。

（修正案１）
データに対して、EUの一般データ保護規則(GDPR)のようなプライバシー関連の法律が適用される場合、また、PCIデータセキュリティスタンダード(PCI DSS)など金融の情報保護の要求があるような規定がある場合には、特に注意が必要です。

（修正案２）
データが、EUの一般データ保護規則(GDPR)のようなプライバシー関連の法律、また、PCIデータセキュリティスタンダード(PCI DSS)など金融の情報保護の要求があるような規定の適用対象となる場合には、特に注意が必要です。

５．0xa5-broken-access-control.md　（てにをは、表現）

「脆弱性発見のポイント」部分

（現訳）
権限昇格。ログインすることなしにユーザとして行動したり、一般ユーザとしてログインした時に管理者として行動できてしまう。
↓
～たり、を使用する場合は、「～たり、～たり」と2回繰り返すのが通常です。

（修正案１）
権限昇格。ログインすることなしにユーザとしてふるまえる。一般ユーザとしてログインした時に管理者としてふるまえる。

※Actingの訳を「ふるまう」にしてみたのですが、「behave」と取れるため、果たして適切か悩むところです。

（修正案２）
権限昇格。ログインすることなしにユーザとして行動したり、一般ユーザとしてログインした時に管理者として行動したりできてしまう。

※文法としては正しいですが、回りくどいかもしれません。

（修正案３）
権限昇格。ログインすることなしにユーザとして行動できてしまう。一般ユーザとしてログインした時に管理者として行動できてしまう。

※文を2つに分けてしまう。

６．0xa6-security-misconfiguration.md　（てにをは、用語の統一）

「脆弱性発見のポイント」部分

アプリケーションスタックのいずれかの部分におけるセキュリティ堅牢化の不足、あるいはクラウドサービスでパーミッションの不適切に設定されている。
↓
アプリケーションスタックのいずれかの部分におけるセキュリティ堅牢化の不足、あるいはクラウドサービスでパーミッションが不適切に設定されている。

「攻撃シナリオの例」部分

シナリオ #4: クラウドサービスプロバイダは、他のCSPユーザによるデフォルトでインターネットに公開された共有パーミッションを用意しています。こうなると、機微なデータがクラウドストレージに保存され、アクセスされてしまいます。
↓
上記の「機微なデータ」を「機微な情報」に修正。

７．0xa9-known-vulns.md　（てにをは、表現）

「脆弱性発見のポイント」部分　4つ目のブレット

これにより、当該企業は、解決済みの脆弱性について、何日も、場合によっては何ヶ月も不必要な危険にさらされることになる
↓
最後に「。」が必要。
また、「当該企業」という部分ですが、原文では「organizations」となっています。読者が全員「企業」とは限らないため「組織」などとしたほうがよいかと思います。後述の「防止方法」の部分では「組織」としているので、用語の統一にもなるかと。

８．0xb3-next-app-mgrs.md　（原文からの抜け）

「計画と設計」部分　最初のブレット

（現訳）
開発者や社内の株主や例えばセキュリティと計画や設計を交渉する。

（原文）
Negotiate planning and design with the developers and internal shareholders, e.g. security specialists.

specialistsの部分が抜けています。

（修正案）
開発者や社内の株主や例えばセキュリティ専門家と計画や設計を交渉する。

９．その他

以下について（どこまで対応すべきか判断つきかねますが）、表記方法にブレが見られます。

ユーザ／ユーザー
サーバ／サーバー（サーバサイド／サーバーサイド も）
ヘッダ／ヘッダー
漏洩／漏えい
サービス拒否／サービス不能（DoSとしているところもあります）
Webアプリケーション／ウェブアプリケーション
技術への影響／技術面への影響（これは、両方存在していてもよいかとも思います）
ビジネスへの影響／ビジネス面への影響（こちらも両方存在していてもよいかと）
マネージャ／マネージャー
カテゴリ／カテゴリー

「事／こと」⇒ 普通（実質）名詞の場合は「事」に（例：事を進める）、形式名詞の場合は「こと」に（例：～すること）
「下さい／ください」⇒ 動詞（give）の場合は「下さい」に（例：りんごを下さい）、補助動詞（please）の場合は「ください」に（例：～してください）

ざっと見た限りでは以上です（すみません、本当にざっとです…）。
ご検討、よろしくお願いいたします。

**Comment by okdt** [comment]
「たり」二回ルールは、Wordの校正ツールでよく指摘されますが、これをカバーするあまり文章が複雑になるような場合には無視して良いです。

**Comment by okdt** [comment]
てにをはを直すあまり、文章のシンプルさや率直さが失われないようにしましょう。

**Comment by okdt** [comment]
以下の伸ばし棒はできるだけなくする方向で。
ユーザ／ユーザー
サーバ／サーバー
ヘッダ／ヘッダー
マネージャ／マネージャー
カテゴリ／カテゴリー

**Comment by okdt** [comment]
「出来ます」「下さい」などはひらがなで開く。

**Comment by shonantoka** [comment]
以下の対応をとりました。
１：修正対応
２：早苗さん対応済みとのことなのでスルー
３：修正案１対応
４：影響　修正対応、ポイント　修正案１対応
５：岡田さんコメントとおりスルー
６：ポイント　修正対応、攻撃シナリオ　修正対応
７：句点の追加及び企業→組織に修正
８：修正対応
９：別途対応
