### ISSUE TITLE
0x02-foreword.md What's Next for関連のドキュメント内リンク

### ISSUE THREAD

**Issue by ogis-sanae** [okdt/Top10#26]
PDF版の原文は、リンクされていますが、日本語版はリンクされていません。

OWASP Top 10のさまざまなユーザーに対して、次のステップを提案しています。「開発者のための次のステップ」、「セキュリティテスト担当者のための次のステップ」、CIOやCISOに適した「組織のための次のステップ」、アプリケーションマネージャやアプリケーションのライフサイクルの責任を持つ人に適した「アプリケーションマネージャのための次のステップ」です。

**Comment by okdt** [comment]
PPTX版を作るときに確認します。
