### ISSUE TITLE
0x05-introduction.md ドキュメント内リンクの差分

### ISSUE THREAD

**Issue by ogis-sanae** [okdt/Top10#27]
下記三点
①原文PDFでは、A8/A10へのドキュメント内リンクあり

今回のメジャーアップデートでは、A8：2017-安全でないデシリアライゼーションとA10：2017-不十分なロギングとモニタリングという2つの問題を含む、いくつかの新しい問題が追加されています。

②原文PDFでは、What's Next forへのドキュメント内リンクがされていました。

定期的に変更する OWASP Top 10はこれからも変化し続けます。また、あなたのアプリケーションコードの、1行も変更していなくても、脆弱になる可能性があります。新しい欠陥が発見され、攻撃方法が洗練されるからです。詳細については、Top 10の最後に掲載した、開発者、テスター、組織、アプリケーションマネージャのための次のステップの項にあるアドバイスを見直してみてください。

③原文PDFでは、ACKへのドキュメント内リンクがされていました。

このドキュメントのスペースに記載できる以上のさらに多くの貢献者がおられますので、その貢献に感謝するための専用ページを作成しました。

非常に建設的なコメントを寄せて頂き、Top 10にこのアップデートを見直す時間をいただいた人たちに感謝します。皆さんのことは、可能な限り「謝辞」のページに記載しています。

**Comment by okdt** [comment]
PPTX版ができたときに・・・
