### ISSUE TITLE
0xa8-insecure-deserializationのRPC/IPC

### ISSUE THREAD

**Issue by ogis-ando** [okdt/Top10#3]
「Remote- and inter-process communication (RPC/IPC)」の訳が12/15時点で「リモートプロシージャコールとプロセス間通信 (RPC/IPC)」となっていますが、「リモート間またはローカル内でのプロセス間通信（RPCやIPC）」ではないかと思います。
プロセス間通信にローカル内でのもの、リモート間でのものという分類があること、リモートプロシージャコールはプロセス間通信の一つの方法であること、によります。
https://ja.wikipedia.org/wiki/%E3%83%97%E3%83%AD%E3%82%BB%E3%82%B9%E9%96%93%E9%80%9A%E4%BF%A1
http://www.coins.tsukuba.ac.jp/~yas/coins/dsys-2008/2008-12-25/

**Comment by ogis-sanae** [comment]
確かに、RPCと書かれていて、略語がほぼ当てはまってしまったので、展開してしまいましたが、実際には、Remote-は、RPCのRではないですね。内部でもRPCが使われることを踏まえ、
「遠隔もしくは内部のプロセス間通信（RPCやIPC）」ではどうでしょうか？

**Comment by ogis-ando** [comment]
「遠隔もしくは内部」だと「どこの」遠隔なのか、内部なのかがわかりにくいと思います。通信がノードのローカル内なのか、リモート間なのか、の方がわかりやすいかと。

**Comment by ogis-sanae** [comment]
では、他のご意見なければ、下記に修正します。
「リモート間またはローカル内でのプロセス間通信（RPCやIPC）」
