### ISSUE TITLE
0xa2-broken-authentication.md　参照の記載に差がある

### ISSUE THREAD

**Issue by ogis-sanae** [okdt/Top10#30]
差分は下記です。
・V3 Session Managementは、ブレットではなく、V2の続きに表記されている
・NIST 800-63bには、日本語にあるような解説の文章は存在していない

**Comment by okdt** [comment]
ひとつめぽつ：PPTX-> PDFの公開版に合わせました。
ふたつめぽつ：ごめんなさい、指摘がわかりませんでした。NIST-800-63に該当する考えを支持することが書かれていないという指摘なのか、英文にない日本語が記載されているという指摘なのか、いずれもチェックしましたが、わかりませんでした。
https://www.nist.gov/i-think-therefore-iam-categories/multi-factor-authentication

**Comment by ogis-sanae** [comment]
岡田さん、二つ目のブレットは、下記の意図です。

英語版：
* [NIST 800-63b: 5.1.1 Memorized Secrets](https://pages.nist.gov/800-63-3/sp800-63b.html#memsecret) 

日本語版：
* [NIST 800-63b: 5.1.1 Memorized Secrets](https://pages.nist.gov/800-63-3/sp800-63b.html#memsecret) - 認証に関して徹底的、現代的かつエビデンスに基づくアドバイスを提供

消した方が良いという提案ではありませんが、下記の文章は、英語版のPDFにはありません。
と言う指摘になります。※英語版のMDファイルには存在しています。

> - 認証に関して徹底的、現代的かつエビデンスに基づくアドバイスを提供

以上よろしくお願いいたします。

**Comment by okdt** [comment]
なるほど、わかりました！
