### ISSUE TITLE
+A: アプリケーションマネージャのための次のステップ

### ISSUE THREAD

**Issue by rdracea** [okdt/Top10#33]
「Manage the Full Application Lifecycle」は「完全なアプリケーションライフサイクルを管理する」ではなく「アプリケーションライフサイクル全体を管理する」のほうがいいと思います。

「Deployment, Testing, Rollout」での「Finalize all documentation...」の「Finalize」は「最終化」というより「確定化」というニュアンスで使われています。

**Comment by shonantoka** [comment]
上記２箇所修正しました
