### ISSUE TITLE
0x00-noticeの public transparencyの訳

### ISSUE THREAD

**Issue by satoichan** [okdt/Top10#4]
public transparencyで定着した訳があるのか、要調査。
英辞郎及び金融庁の資料では「公共の透明性」という表現。
金融庁資料	http://www.fsa.go.jp/inter/ios/20170822.html

http://rtd-denver.com/PublicTransparency.shtml
のような表現をしているところを見ると、何かある気がする

**Comment by okdt** [comment]
「公共の透明性」と書いたほうが良いという指摘ですか。githubで指摘事項を追跡できるということは、概念レベルの公共の透明性とはちょっとニュアンスが違う気がしますし、public commentなどOWASPでは普通のプロセスですので、行政用語にする必要はないものと思います。

が、とくにそれで収まりが悪くなるわけでもないので、ご指摘どおりそうしておきます。
ご指摘に感謝します。
