### ISSUE TITLE
0x01-about-owasp 表現修正5か所

### ISSUE THREAD

**Issue by satoichan** [okdt/Top10#5]
pushはしていません。
行数は訳文のものです。
ご検討ください。

【5行目】
The Open Web Application Security Project (OWASP/日本語: オワスプ) は、オープンなコミュニティであり、組織がアプリケーションやAPIを開発、調達、メンテナンスするにあたりそれらが信頼できるようになることに注力しています。
【7行目】
OWASPでは、以下がフリーで公開されています。
【10行目】
* アプリケーションセキュリティテスト、セキュアなコード開発、セキュアなコードレビューについての完成図書。
【27行目】
OWASPは、どのようなテクノロジ企業とも提携しません。しかしながら、詳細な情報を得た上での商用セキュリティ技術を利用することについてはサポートします。OWASPは、さまざまな種類の資料を共同で、透明で、オープンな方法で制作します。
【29行目】
The OWASP Foundation(オワスプ・ファウンデーション)は、プロジェクトの長期的な成功を実現する非営利団体です。OWASPに関わるほとんどの人すなわちOWASPボード、チャプターリーダー、プロジェクトリーダー、プロジェクトメンバーはボランティアです。私たちは、革新的なセキュリティリサーチに対しては、金銭面とインフラストラクチャを提供することによってサポートします。

**Comment by okdt** [comment]
5行目についての提案: 現状の文より意味が不明です。

**Comment by okdt** [comment]
7行目への提案: 「以下が」は言葉としておかしいです。
freeとフリーは、オープンソースの世界では全く意味が違います。前者は利用の自由を示しており、後者は無料であることを主に示しています。

**Comment by okdt** [comment]
10行目への提案: 「完成図書」そんな言葉はありませんし意味が不明です。

**Comment by okdt** [comment]
27行目、29行目への提案: 改善提案あるいは指摘のポイントが今ひとつわかりません。

**Comment by satoichan** [comment]
「意味が不明」？
おっしゃりたいことがよく分からないのですが、あらためておさまりの悪いところを指摘しておきます。

5行目について
もっぱら専念→重ね言葉になってる

**Comment by satoichan** [comment]
7行目について
「状況をご覧になれます」
・箇条書きの部分は「状況」ではない
・本文は丁寧語で表記することになっているのに、敬語を使っている

**Comment by okdt** [comment]
そう書いてくだささればわかります。

**Comment by okdt** [comment]
https://github.com/okdt/Top10/commit/e5a2382609194841e8ab1280d0fe0800338e6ffd#diff-6a07e993e7a9d786a08b288be6865bec
