### ISSUE TITLE
flaw の日本語訳

### ISSUE THREAD

**Issue by naotokatsumi** [okdt/Top10#6]
同じページ内で flaw, vulnerability が使われた場合、flaw, vulnerability ともに「脆弱性」と訳してはどうかと考えています。いかがでしょうか。

[A1:2017-Injection (ja)](https://github.com/okdt/Top10/blob/master/2017/ja/0xa1-injection.md) をレビューしたときに、「[インジェクション欠陥](https://www.owasp.org/index.php/Injection_Flaws)」の表現に悩みました。同ページの他の文章で「脆弱性」という表現も使われており、「脆弱性」・「欠陥」が混在しています。このように、flaw が vulnerability を意味しているような場合、flaw を「脆弱性」を訳すと、表現と統一でき読みやすさが向上すると考えます。

**Comment by okdt** [comment]
いいえ。flawとvulnerabilityは全く別の言葉です。flawは欠陥、vulnerabilityはその結果としてシステムに現れる出てくる脆弱性です。同一訳語にすることはあり得ません。

**Comment by naotokatsumi** [comment]
コメントありがとうございます。

欠陥と脆弱性が別の概念ということですね。私は「欠陥」の中のうち悪用できるものを「脆弱性」と考えていて、このように Issue を立てました。

flaw: 欠陥、vulnerability: 脆弱性(flaw の結果としてシステムに現れる/出てくるもの) として進めます。

**Comment by okdt** [comment]
サクサク要点だけ回答しています。ストレートですみません。
