### ISSUE TITLE
0x02-foreword.md タイトルの不整合

### ISSUE THREAD

**Issue by ogis-sanae** [okdt/Top10#8]
0x02-foreword.mdでは、下記の記述

> OWASP Top 10のさまざまなユーザーに対して、次のステップを提案しています。「開発者の次のステップ」、「セキュリティチームの次のステップ」、「セキュリティテストチームの次のステップ」、CIOやCISOに適した「組織にとっての次のステップ」、アプリケーションマネージャやアプリケーションのライフサイクルの責任を持つ人に適した「アプリケーションマネージャの次のステップ」です。

※ちなみに、セキュリティチームの次のステップは、元の英文にもないようです。

> We have written up a range of suggested next steps for different users of the OWASP Top 10, including "What's Next for Developers", "What's Next for Security Testers", "What's Next for Organizations“, which is suitable for CIOs and CISOs, and "What's Next for Application Managers", which is suitable for application managers or anyone responsible for the lifecycle of the application.

各タイトルは、
> 開発者向けの次のステップ
> セキュリティテスト担当者のための次のステップ
> 組織のための次のステップ
> アプリケーションマネージャのための次のステップ

どちらに統一しましょうか？
また、他の所は リンクを張っていますが、ここはリンクがないです。ここのリンクは追加した方が使いやすいのではないかと思います。

**Comment by okdt** [comment]
和文は英文にあわせます。リンクはなくていいと思います。あらゆるハイパーリンクを統一して展開することは煩雑ですし。
ありがとうございます。

**Comment by okdt** [comment]
「〜のための...」にあわせます。

**Comment by ogis-sanae** [comment]
了解です。
・リンクはしない
・「セキュリティチームの次のステップ」は英文にないので削除
・各タイトルは、～のためのに統一
> 開発者のための次のステップ ⇒ 変更になります。
> セキュリティテスト担当者のための次のステップ
> 組織のための次のステップ
> アプリケーションマネージャのための次のステップ

**Comment by okdt** [comment]
一応、レポジトリのほうは直したつもりです。ご確認ください。

**Comment by ogis-sanae** [comment]
確認いたしました。ありがとうございました。
