### ISSUE TITLE
ドキュメントタイトル・表項目の統一

### ISSUE THREAD

**Issue by ogis-sanae** [okdt/Top10#9]
OWASP Top 10のタイトルと表の中の項目名が全ページで統一されていない

t10のファイルに準じて一括して修正して良いでしょうか？

t10では、A3だけ、機微データの露出になっているので、議論を踏まえ、機微な情報の露出で統一しようと思います。また、項目名は議論を踏まえ、0xa1-injection.mdをベースに統一しようと思います。ただ、「技術面への影響」「ビジネス面への影響」は、表の中では、上の段に「影響」としてくくりだしているわけなので、重複表現になるので単に「技術面」「ビジネス面」だけで十分ではないかと思いますがいかがでしょうか？

ページタイトルについて、「A1:2017-インジェクション」か「A1:2017 インジェクション」どちらで統一しましょうか？
「-」の有無です。英語版は、元々なかったみたいですが後で入れたようです。
ただ日本語的には、「-」は無い方が見やすい気もします。

**Comment by okdt** [comment]
1. おっしゃることはわかりますが、タイトルとして 「技術面への影響」「ビジネス面への影響」でいかがでしょうか。技術面、ビジネス面だけではストレートに意味がわからないからです。

2. 「-」ですが、いれておきましょう。区切り文字の意味合いもあるんだと思います。

**Comment by ogis-sanae** [comment]
どちらも了解です。特に異論ありません。
